/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[20];
new PlayerText:PlayerTD[MAX_PLAYERS][7];

//Textdraws
PublicTD[0] = TextDrawCreate(553.000000, 101.000000, "_");
TextDrawFont(PublicTD[0], 1);
TextDrawLetterSize(PublicTD[0], 0.516665, 1.000002);
TextDrawTextSize(PublicTD[0], 345.500000, 107.000000);
TextDrawSetOutline(PublicTD[0], 1);
TextDrawSetShadow(PublicTD[0], 0);
TextDrawAlignment(PublicTD[0], 2);
TextDrawColor(PublicTD[0], -1);
TextDrawBackgroundColor(PublicTD[0], 255);
TextDrawBoxColor(PublicTD[0], 111);
TextDrawUseBox(PublicTD[0], 1);
TextDrawSetProportional(PublicTD[0], 1);
TextDrawSetSelectable(PublicTD[0], 0);

PublicTD[1] = TextDrawCreate(584.000000, 296.000000, "_");
TextDrawFont(PublicTD[1], 1);
TextDrawLetterSize(PublicTD[1], 0.600000, 6.400002);
TextDrawTextSize(PublicTD[1], 298.500000, 100.000000);
TextDrawSetOutline(PublicTD[1], 1);
TextDrawSetShadow(PublicTD[1], 0);
TextDrawAlignment(PublicTD[1], 2);
TextDrawColor(PublicTD[1], -1);
TextDrawBackgroundColor(PublicTD[1], 255);
TextDrawBoxColor(PublicTD[1], 105);
TextDrawUseBox(PublicTD[1], 1);
TextDrawSetProportional(PublicTD[1], 1);
TextDrawSetSelectable(PublicTD[1], 0);

PublicTD[2] = TextDrawCreate(603.000000, 301.000000, "_");
TextDrawFont(PublicTD[2], 1);
TextDrawLetterSize(PublicTD[2], 0.600000, 0.800002);
TextDrawTextSize(PublicTD[2], 303.500000, 55.000000);
TextDrawSetOutline(PublicTD[2], 1);
TextDrawSetShadow(PublicTD[2], 0);
TextDrawAlignment(PublicTD[2], 2);
TextDrawColor(PublicTD[2], -1);
TextDrawBackgroundColor(PublicTD[2], 255);
TextDrawBoxColor(PublicTD[2], 135);
TextDrawUseBox(PublicTD[2], 1);
TextDrawSetProportional(PublicTD[2], 1);
TextDrawSetSelectable(PublicTD[2], 0);

PublicTD[3] = TextDrawCreate(603.000000, 314.000000, "_");
TextDrawFont(PublicTD[3], 1);
TextDrawLetterSize(PublicTD[3], 0.600000, 0.800002);
TextDrawTextSize(PublicTD[3], 303.500000, 55.000000);
TextDrawSetOutline(PublicTD[3], 1);
TextDrawSetShadow(PublicTD[3], 0);
TextDrawAlignment(PublicTD[3], 2);
TextDrawColor(PublicTD[3], -1);
TextDrawBackgroundColor(PublicTD[3], 255);
TextDrawBoxColor(PublicTD[3], 135);
TextDrawUseBox(PublicTD[3], 1);
TextDrawSetProportional(PublicTD[3], 1);
TextDrawSetSelectable(PublicTD[3], 0);

PublicTD[4] = TextDrawCreate(603.000000, 328.000000, "_");
TextDrawFont(PublicTD[4], 1);
TextDrawLetterSize(PublicTD[4], 0.600000, 0.800002);
TextDrawTextSize(PublicTD[4], 303.500000, 55.000000);
TextDrawSetOutline(PublicTD[4], 1);
TextDrawSetShadow(PublicTD[4], 0);
TextDrawAlignment(PublicTD[4], 2);
TextDrawColor(PublicTD[4], -1);
TextDrawBackgroundColor(PublicTD[4], 255);
TextDrawBoxColor(PublicTD[4], 135);
TextDrawUseBox(PublicTD[4], 1);
TextDrawSetProportional(PublicTD[4], 1);
TextDrawSetSelectable(PublicTD[4], 0);

PublicTD[5] = TextDrawCreate(603.000000, 342.000000, "_");
TextDrawFont(PublicTD[5], 1);
TextDrawLetterSize(PublicTD[5], 0.600000, 0.800002);
TextDrawTextSize(PublicTD[5], 303.500000, 55.000000);
TextDrawSetOutline(PublicTD[5], 1);
TextDrawSetShadow(PublicTD[5], 0);
TextDrawAlignment(PublicTD[5], 2);
TextDrawColor(PublicTD[5], -1);
TextDrawBackgroundColor(PublicTD[5], 255);
TextDrawBoxColor(PublicTD[5], 135);
TextDrawUseBox(PublicTD[5], 1);
TextDrawSetProportional(PublicTD[5], 1);
TextDrawSetSelectable(PublicTD[5], 0);

PublicTD[6] = TextDrawCreate(542.000000, 343.000000, "Preview_Model");
TextDrawFont(PublicTD[6], 5);
TextDrawLetterSize(PublicTD[6], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[6], 100.000000, 123.000000);
TextDrawSetOutline(PublicTD[6], 0);
TextDrawSetShadow(PublicTD[6], 0);
TextDrawAlignment(PublicTD[6], 1);
TextDrawColor(PublicTD[6], -1);
TextDrawBackgroundColor(PublicTD[6], 0);
TextDrawBoxColor(PublicTD[6], 255);
TextDrawUseBox(PublicTD[6], 0);
TextDrawSetProportional(PublicTD[6], 1);
TextDrawSetSelectable(PublicTD[6], 0);
TextDrawSetPreviewModel(PublicTD[6], 18863);
TextDrawSetPreviewRot(PublicTD[6], -7.000000, 0.000000, -40.000000, 1.000000);
TextDrawSetPreviewVehCol(PublicTD[6], 1, 1);

PublicTD[7] = TextDrawCreate(542.000000, 343.000000, "Preview_Model");
TextDrawFont(PublicTD[7], 5);
TextDrawLetterSize(PublicTD[7], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[7], 100.000000, 123.000000);
TextDrawSetOutline(PublicTD[7], 0);
TextDrawSetShadow(PublicTD[7], 0);
TextDrawAlignment(PublicTD[7], 1);
TextDrawColor(PublicTD[7], -1);
TextDrawBackgroundColor(PublicTD[7], 0);
TextDrawBoxColor(PublicTD[7], 255);
TextDrawUseBox(PublicTD[7], 0);
TextDrawSetProportional(PublicTD[7], 1);
TextDrawSetSelectable(PublicTD[7], 0);
TextDrawSetPreviewModel(PublicTD[7], 18863);
TextDrawSetPreviewRot(PublicTD[7], -7.000000, 0.000000, -40.000000, 1.000000);
TextDrawSetPreviewVehCol(PublicTD[7], 1, 1);

PublicTD[8] = TextDrawCreate(552.000000, 326.000000, "Preview_Model");
TextDrawFont(PublicTD[8], 5);
TextDrawLetterSize(PublicTD[8], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[8], 100.000000, 123.000000);
TextDrawSetOutline(PublicTD[8], 0);
TextDrawSetShadow(PublicTD[8], 0);
TextDrawAlignment(PublicTD[8], 1);
TextDrawColor(PublicTD[8], -1);
TextDrawBackgroundColor(PublicTD[8], 0);
TextDrawBoxColor(PublicTD[8], 255);
TextDrawUseBox(PublicTD[8], 0);
TextDrawSetProportional(PublicTD[8], 1);
TextDrawSetSelectable(PublicTD[8], 0);
TextDrawSetPreviewModel(PublicTD[8], 18863);
TextDrawSetPreviewRot(PublicTD[8], -7.000000, 0.000000, -40.000000, 1.000000);
TextDrawSetPreviewVehCol(PublicTD[8], 1, 1);

PublicTD[9] = TextDrawCreate(552.000000, 326.000000, "Preview_Model");
TextDrawFont(PublicTD[9], 5);
TextDrawLetterSize(PublicTD[9], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[9], 100.000000, 123.000000);
TextDrawSetOutline(PublicTD[9], 0);
TextDrawSetShadow(PublicTD[9], 0);
TextDrawAlignment(PublicTD[9], 1);
TextDrawColor(PublicTD[9], -1);
TextDrawBackgroundColor(PublicTD[9], 0);
TextDrawBoxColor(PublicTD[9], 255);
TextDrawUseBox(PublicTD[9], 0);
TextDrawSetProportional(PublicTD[9], 1);
TextDrawSetSelectable(PublicTD[9], 0);
TextDrawSetPreviewModel(PublicTD[9], 18863);
TextDrawSetPreviewRot(PublicTD[9], -7.000000, 0.000000, -40.000000, 1.000000);
TextDrawSetPreviewVehCol(PublicTD[9], 1, 1);

PublicTD[10] = TextDrawCreate(568.000000, 341.000000, "Preview_Model");
TextDrawFont(PublicTD[10], 5);
TextDrawLetterSize(PublicTD[10], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[10], 92.500000, 120.000000);
TextDrawSetOutline(PublicTD[10], 0);
TextDrawSetShadow(PublicTD[10], 0);
TextDrawAlignment(PublicTD[10], 1);
TextDrawColor(PublicTD[10], -1);
TextDrawBackgroundColor(PublicTD[10], 0);
TextDrawBoxColor(PublicTD[10], 255);
TextDrawUseBox(PublicTD[10], 0);
TextDrawSetProportional(PublicTD[10], 1);
TextDrawSetSelectable(PublicTD[10], 0);
TextDrawSetPreviewModel(PublicTD[10], 19076);
TextDrawSetPreviewRot(PublicTD[10], -5.000000, 0.000000, -26.000000, 1.000000);
TextDrawSetPreviewVehCol(PublicTD[10], 1, 1);

PublicTD[11] = TextDrawCreate(593.000000, 426.000000, "Preview_Model");
TextDrawFont(PublicTD[11], 5);
TextDrawLetterSize(PublicTD[11], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[11], 17.500000, 20.000000);
TextDrawSetOutline(PublicTD[11], 0);
TextDrawSetShadow(PublicTD[11], 0);
TextDrawAlignment(PublicTD[11], 1);
TextDrawColor(PublicTD[11], -1);
TextDrawBackgroundColor(PublicTD[11], 1090519040);
TextDrawBoxColor(PublicTD[11], 255);
TextDrawUseBox(PublicTD[11], 0);
TextDrawSetProportional(PublicTD[11], 1);
TextDrawSetSelectable(PublicTD[11], 0);
TextDrawSetPreviewModel(PublicTD[11], 19054);
TextDrawSetPreviewRot(PublicTD[11], -10.000000, 0.000000, -44.000000, 1.000000);
TextDrawSetPreviewVehCol(PublicTD[11], 1, 1);

PublicTD[12] = TextDrawCreate(531.000000, 356.000000, "LD_spac:white");
TextDrawFont(PublicTD[12], 4);
TextDrawLetterSize(PublicTD[12], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[12], 104.500000, -1.500000);
TextDrawSetOutline(PublicTD[12], 1);
TextDrawSetShadow(PublicTD[12], 0);
TextDrawAlignment(PublicTD[12], 1);
TextDrawColor(PublicTD[12], 255);
TextDrawBackgroundColor(PublicTD[12], 255);
TextDrawBoxColor(PublicTD[12], 50);
TextDrawUseBox(PublicTD[12], 1);
TextDrawSetProportional(PublicTD[12], 1);
TextDrawSetSelectable(PublicTD[12], 0);

PublicTD[13] = TextDrawCreate(538.000000, 293.000000, "SESSION");
TextDrawFont(PublicTD[13], 2);
TextDrawLetterSize(PublicTD[13], 0.129166, 1.099998);
TextDrawTextSize(PublicTD[13], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[13], 0);
TextDrawSetShadow(PublicTD[13], 0);
TextDrawAlignment(PublicTD[13], 1);
TextDrawColor(PublicTD[13], 1097458175);
TextDrawBackgroundColor(PublicTD[13], 255);
TextDrawBoxColor(PublicTD[13], 50);
TextDrawUseBox(PublicTD[13], 0);
TextDrawSetProportional(PublicTD[13], 1);
TextDrawSetSelectable(PublicTD[13], 0);

PublicTD[14] = TextDrawCreate(576.000000, 300.000000, "KILLS");
TextDrawFont(PublicTD[14], 2);
TextDrawLetterSize(PublicTD[14], 0.125000, 0.899999);
TextDrawTextSize(PublicTD[14], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[14], 0);
TextDrawSetShadow(PublicTD[14], 0);
TextDrawAlignment(PublicTD[14], 1);
TextDrawColor(PublicTD[14], -1);
TextDrawBackgroundColor(PublicTD[14], 255);
TextDrawBoxColor(PublicTD[14], 50);
TextDrawUseBox(PublicTD[14], 0);
TextDrawSetProportional(PublicTD[14], 1);
TextDrawSetSelectable(PublicTD[14], 0);

PublicTD[15] = TextDrawCreate(576.000000, 313.000000, "DEATHS");
TextDrawFont(PublicTD[15], 2);
TextDrawLetterSize(PublicTD[15], 0.125000, 0.899999);
TextDrawTextSize(PublicTD[15], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[15], 0);
TextDrawSetShadow(PublicTD[15], 0);
TextDrawAlignment(PublicTD[15], 1);
TextDrawColor(PublicTD[15], -1);
TextDrawBackgroundColor(PublicTD[15], 255);
TextDrawBoxColor(PublicTD[15], 50);
TextDrawUseBox(PublicTD[15], 0);
TextDrawSetProportional(PublicTD[15], 1);
TextDrawSetSelectable(PublicTD[15], 0);

PublicTD[16] = TextDrawCreate(576.000000, 327.000000, "RATIO");
TextDrawFont(PublicTD[16], 2);
TextDrawLetterSize(PublicTD[16], 0.125000, 0.899999);
TextDrawTextSize(PublicTD[16], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[16], 0);
TextDrawSetShadow(PublicTD[16], 0);
TextDrawAlignment(PublicTD[16], 1);
TextDrawColor(PublicTD[16], -1);
TextDrawBackgroundColor(PublicTD[16], 255);
TextDrawBoxColor(PublicTD[16], 50);
TextDrawUseBox(PublicTD[16], 0);
TextDrawSetProportional(PublicTD[16], 1);
TextDrawSetSelectable(PublicTD[16], 0);

PublicTD[17] = TextDrawCreate(576.000000, 341.000000, "STREAK");
TextDrawFont(PublicTD[17], 2);
TextDrawLetterSize(PublicTD[17], 0.125000, 0.899999);
TextDrawTextSize(PublicTD[17], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[17], 0);
TextDrawSetShadow(PublicTD[17], 0);
TextDrawAlignment(PublicTD[17], 1);
TextDrawColor(PublicTD[17], -1);
TextDrawBackgroundColor(PublicTD[17], 255);
TextDrawBoxColor(PublicTD[17], 50);
TextDrawUseBox(PublicTD[17], 0);
TextDrawSetProportional(PublicTD[17], 1);
TextDrawSetSelectable(PublicTD[17], 0);

PublicTD[18] = TextDrawCreate(11.000000, 422.000000, "19:55:26");
TextDrawFont(PublicTD[18], 3);
TextDrawLetterSize(PublicTD[18], 0.245832, 0.899999);
TextDrawTextSize(PublicTD[18], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[18], 1);
TextDrawSetShadow(PublicTD[18], 0);
TextDrawAlignment(PublicTD[18], 1);
TextDrawColor(PublicTD[18], 1097458175);
TextDrawBackgroundColor(PublicTD[18], 255);
TextDrawBoxColor(PublicTD[18], 50);
TextDrawUseBox(PublicTD[18], 0);
TextDrawSetProportional(PublicTD[18], 1);
TextDrawSetSelectable(PublicTD[18], 0);

PublicTD[19] = TextDrawCreate(16.000000, 431.000000, "20/01/2019");
TextDrawFont(PublicTD[19], 3);
TextDrawLetterSize(PublicTD[19], 0.254166, 0.949999);
TextDrawTextSize(PublicTD[19], 400.000000, 17.000000);
TextDrawSetOutline(PublicTD[19], 1);
TextDrawSetShadow(PublicTD[19], 0);
TextDrawAlignment(PublicTD[19], 1);
TextDrawColor(PublicTD[19], -1);
TextDrawBackgroundColor(PublicTD[19], 255);
TextDrawBoxColor(PublicTD[19], 50);
TextDrawUseBox(PublicTD[19], 0);
TextDrawSetProportional(PublicTD[19], 1);
TextDrawSetSelectable(PublicTD[19], 0);


//Player Textdraws
PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 530.000000, 100.000000, "FPS:~w~ 99");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.166666, 1.100000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 3);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], 1097458175);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 597.000000, 100.000000, "PING: ~w~53");
PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.166666, 1.100000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 3);
PlayerTextDrawColor(playerid, PlayerTD[playerid][1], 1097458175);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 521.000000, 306.000000, "Preview_Model");
PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 5);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 62.500000, 45.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 255);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawSetPreviewModel(playerid, PlayerTD[playerid][2], 249);
PlayerTextDrawSetPreviewRot(playerid, PlayerTD[playerid][2], -10.000000, 0.000000, -3.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, PlayerTD[playerid][2], 1, 1);

PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 625.000000, 299.000000, "0");
PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.166666, 1.099998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][3], 1097458175);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 625.000000, 312.000000, "0");
PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.166666, 1.099998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][4], 1097458175);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);

PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 615.000000, 326.000000, "0.00");
PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.166666, 1.099998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][5], 1097458175);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);

PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 625.000000, 340.000000, "0");
PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.166666, 1.099998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][6], 1097458175);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
