forward ipCheck(extraID);
forward aliasCheck(extraID);
forward banInfo(playerid);
forward sql_OnAccountCreate(playerid);
forward HitRemove(playerid);
forward DeathTimer(playerid);
forward Free(playerid);
forward UnFreezePlayer(playerid);
forward Loading(playerid);
forward Loaded(playerid);
forward sql_checkIP(playerid);
forward sql_returnbanned(playerid);
forward checkIPUnban(playerid, const checkIP[]);
forward CheckUnban(playerid, user_name[]);
forward check_account_registered(playerid);
forward sql_LoadPlayerData(playerid);
forward CheckAccountIsRegForLogin(playerid);
forward KickDelay(playerid);
forward StopSpectate(playerid);
forward Admini(playerid);
forward Premiums(playerid);
forward sql_user_update_integer( playerid, field[], value );
forward sql_user_update_string(playerid, field[], val[]);
forward sql_user_update_float(playerid, field[], Float: val);